export const BOOKING_LIST_REQUEST = "BOOKING_LIST_REQUEST";
export const BOOKING_LIST_SUCCESS = "BOOKING_LIST_SUCCESS";
export const BOOKING_LIST_FAIL = "BOOKING_LIST_FAIL";

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST";
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL";

export const BOOKING_PAID_REQUEST = "BOOKING_PAID_REQUEST";
export const BOOKING_PAID_SUCCESS = "BOOKING_PAID_SUCCESS";
export const BOOKING_PAID_FAIL = "BOOKING_PAID_FAIL";
export const BOOKING_PAID_RESET = "BOOKING_PAID_RESET";
