export const RESTAURANT_LIST_REQUEST = "RESTAURANT_LIST_REQUEST";
export const RESTAURANT_LIST_SUCCESS = "RESTAURANT_LIST_SUCCESS";
export const RESTAURANT_LIST_FAIL = "RESTAURANT_LIST_FAIL";

export const RESTAURANT_EDIT_REQUEST = "RESTAURANT_EDIT_REQUEST";
export const RESTAURANT_EDIT_SUCCESS = "RESTAURANT_EDIT_SUCCESS";
export const RESTAURANT_EDIT_FAIL = "RESTAURANT_EDIT_FAIL";

export const RESTAURANT_DELETE_REQUEST = "RESTAURANT_DELETE_REQUEST";
export const RESTAURANT_DELETE_SUCCESS = "RESTAURANT_DELETE_SUCCESS";
export const RESTAURANT_DELETE_FAIL = "RESTAURANT_DELETE_FAIL";

export const RESTAURANT_CREATE_REQUEST = "RESTAURANT_CREATE_REQUEST";
export const RESTAURANT_CREATE_SUCCESS = "RESTAURANT_CREATE_SUCCESS";
export const RESTAURANT_CREATE_FAIL = "RESTAURANT_CREATE_FAIL";
export const RESTAURANT_CREATE_RESET = "RESTAURANT_CREATE_RESET";

export const RESTAURANT_UPDATE_REQUEST = "RESTAURANT_UPDATE_REQUEST";
export const RESTAURANT_UPDATE_SUCCESS = "RESTAURANT_UPDATE_SUCCESS";
export const RESTAURANT_UPDATE_FAIL = "RESTAURANT_UPDATE_FAIL";
export const RESTAURANT_UPDATE_RESET = "RESTAURANT_UPDATE_RESET";

export const RESTAURANT_BY_OWNERS_REQUEST = "RESTAURANT_BY_OWNERS_REQUEST";
export const RESTAURANT_BY_OWNERS_SUCCESS = "RESTAURANT_BY_OWNERS_SUCCESS";
export const RESTAURANT_BY_OWNERS_FAIL = "RESTAURANT_BY_OWNERS_FAIL";
