export const TABLE_LIST_REQUEST = "TABLE_LIST_REQUEST";
export const TABLE_LIST_SUCCESS = "TABLE_LIST_SUCCESS";
export const TABLE_LIST_FAIL = "TABLE_LIST_FAIL";

export const TABLE_EDIT_REQUEST = "TABLE_EDIT_REQUEST";
export const TABLE_EDIT_SUCCESS = "TABLE_EDIT_SUCCESS";
export const TABLE_EDIT_FAIL = "TABLE_EDIT_FAIL";

export const TABLE_DELETE_REQUEST = "TABLE_DELETE_REQUEST";
export const TABLE_DELETE_SUCCESS = "TABLE_DELETE_SUCCESS";
export const TABLE_DELETE_FAIL = "TABLE_DELETE_FAIL";

export const TABLE_CREATE_REQUEST = "TABLE_CREATE_REQUEST";
export const TABLE_CREATE_SUCCESS = "TABLE_CREATE_SUCCESS";
export const TABLE_CREATE_FAIL = "TABLE_CREATE_FAIL";
export const TABLE_CREATE_RESET = "TABLE_CREATE_RESET";

export const TABLE_UPDATE_REQUEST = "TABLE_UPDATE_REQUEST";
export const TABLE_UPDATE_SUCCESS = "TABLE_UPDATE_SUCCESS";
export const TABLE_UPDATE_FAIL = "TABLE_UPDATE_FAIL";
export const TABLE_UPDATE_RESET = "TABLE_UPDATE_RESET";
